---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:ItamarLevin/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/indigo-octagon-267011/echo
      tag: latest
